
# Site settings

twitter_username: fredzannarbor
github_username:  fredzannarbor
linkedin_username: wfzimmerman

theme: minima
title: Fred Zimmerman

collections: 
  books_in_print:
    output: true
    permalink: /:collection/:name

  altbrains:
    
  achievement_bullets:

google_analytics: UA-115655326-3

defaults:
 scope:
     path: ""
     type: "books_in_prints"
   values:
     layout: "books_in_print"
 scope:
     path: ""
     type: "posts"
   values:
     layout: "post"
 scope:
     path: ""
     type: "pages"
   values:
     layout: "page"
 scope:
     path: ""
   values:
     layout: "default"

