
# Site settings

twitter_username: fredzannarbor
github_username:  fredzannarbor
linkedin_username: wfzimmerman

theme: minima
title: Fred Zimmerman

collections:
  books_in_print:
    output: true
    permalink: /:collection/:name

  altbrains:

  achievements:
    output: true
    permalink: /:collection/:name

  employers:
    output: true
    permalink: /:collection/:name

google_analytics: UA-115655326-3



defaults:
  - scope:
      path: ""
      type: "books_in_print"
    values:
      layout: "books_in_print"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "achievements"
    values:
      layout: "achievement"
  - scope:
      path: ""
      type: "employers"
    values:
      layout: "employer"
  # - scope:
  #     path: ""
  #     type: "resume"
  #   values:
  #      layout: "achievement"
