# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
twitter_username: fredzannarbor
github_username:  fredzannarbor

theme: minima
title: Fred Zimmerman

collections: 
  books_in_print:
    output: true
    permalink: /:collection/:name
    
  altbrains:
  achievement_bullets:

google_analytics: UA-115655326-3

url: "https://fredzannarbor.github.io/fredzannarbor"

defaults:
  - scope:
      path: ""
      type: "books_in_print"
    values:
      layout: "books_in_print"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:  
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"