
# Site settings

twitter_username: fredzannarbor
github_username:  fredzannarbor
linkedin_username: wfzimmerman

plugins:
  - jekyll-sitemap

theme: minima
title: Fred Zimmerman's Website

collections:
  books_in_print:
    output: true
    permalink: /:collection/:name

  altbrains:
    output: true 
    permalink: /:collection/:name

  accomplishments:
    output: true
    permalink: /:collection/:name

  employers:
    output: true
    permalink: /:collection/:name


  content:
    output: true 
    permalink: /:collection/:name

google_analytics: UA-115655326-3

header_pages:
  - about.html

defaults:
  - scope:
      path: ""
      type: "books_in_print"
    values:
      layout: "books_in_print"
  - scope:
      path: ""
      type: "content"
    values:
      layout: "content"
  - scope:
      path: ""
      type: "altbrains"
    values:
      layout: "altbrains"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "accomplishments"
    values:
      layout: "accomplishment"
  - scope:
      path: ""
      type: "employers"
    values:
      layout: "employer"
  # - scope:
  #     path: ""
  #     type: "resume"
  #   values:
  #      layout: "accomplishment"
